#!/bin/sh

while true ; do
	acpi -b | while read line ; do

		batnum=`echo $line |  sed 's/^Battery \(.\).*/\1/'`
		percent=`echo $line | sed 's/.* \([0-9]*%\).*/\1/'`
		if echo $line | grep -q Discharging ; then
			color='#CC7777'
			tleft=`echo $line | sed 's/.*\(..:..:..\).*/\1/'`
		else
			color='#77CC77'
		fi

		echo "<span color='$color'>BAT#$batnum $percent $tleft</span>"

	done

	sleep 20
done

